package hospital_gestion.modelo;
// Generated 03-feb-2024 18:42:45 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Medicos generated by hbm2java
 */
public class Medicos implements java.io.Serializable {

    private Long id;
    private String numeroColegiado;
    private String dni;
    private String nombre;
    private String apellido1;
    private String apellido2;
    private String telefono;
    private Set citases = new HashSet(0);

    public Medicos() {
    }

    public Medicos(String numeroColegiado, String dni, String nombre, String apellido1) {
        this.numeroColegiado = numeroColegiado;
        this.dni = dni;
        this.nombre = nombre;
        this.apellido1 = apellido1;
    }

    public Medicos(String numeroColegiado, String dni, String nombre, String apellido1, String apellido2, String telefono, Set citases) {
        this.numeroColegiado = numeroColegiado;
        this.dni = dni;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.telefono = telefono;
        this.citases = citases;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNumeroColegiado() {
        return this.numeroColegiado;
    }

    public void setNumeroColegiado(String numeroColegiado) {
        this.numeroColegiado = numeroColegiado;
    }

    public String getDni() {
        return this.dni;
    }

    public void setDni(String dni) {
        this.dni = dni;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido1() {
        return this.apellido1;
    }

    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }

    public String getApellido2() {
        return this.apellido2;
    }

    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public Set getCitases() {
        return this.citases;
    }

    public void setCitases(Set citases) {
        this.citases = citases;
    }

}
