package hospital_gestion.modelo;
// Generated 02-feb-2024 1:53:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Medicos generated by hbm2java
 */
public class Medicos  implements java.io.Serializable {


     private Long id;
     private String numeroColegiado;
     private String dni;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String telefono;
     private String sexo;
     private long especialidadId;
     private Long horarioId;
     private Long userId;
     private Date createdAt;
     private Date updatedAt;
     private Set pacienteses = new HashSet(0);
     private Set citases = new HashSet(0);

    public Medicos() {
    }

	
    public Medicos(String numeroColegiado, String dni, String nombre, String apellido1, long especialidadId) {
        this.numeroColegiado = numeroColegiado;
        this.dni = dni;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.especialidadId = especialidadId;
    }
    public Medicos(String numeroColegiado, String dni, String nombre, String apellido1, String apellido2, String telefono, String sexo, long especialidadId, Long horarioId, Long userId, Date createdAt, Date updatedAt, Set pacienteses, Set citases) {
       this.numeroColegiado = numeroColegiado;
       this.dni = dni;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.telefono = telefono;
       this.sexo = sexo;
       this.especialidadId = especialidadId;
       this.horarioId = horarioId;
       this.userId = userId;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.pacienteses = pacienteses;
       this.citases = citases;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNumeroColegiado() {
        return this.numeroColegiado;
    }
    
    public void setNumeroColegiado(String numeroColegiado) {
        this.numeroColegiado = numeroColegiado;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public long getEspecialidadId() {
        return this.especialidadId;
    }
    
    public void setEspecialidadId(long especialidadId) {
        this.especialidadId = especialidadId;
    }
    public Long getHorarioId() {
        return this.horarioId;
    }
    
    public void setHorarioId(Long horarioId) {
        this.horarioId = horarioId;
    }
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set getPacienteses() {
        return this.pacienteses;
    }
    
    public void setPacienteses(Set pacienteses) {
        this.pacienteses = pacienteses;
    }
    public Set getCitases() {
        return this.citases;
    }
    
    public void setCitases(Set citases) {
        this.citases = citases;
    }




}


