package hospital_gestion.modelo;
// Generated 03-feb-2024 18:42:45 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pacientes generated by hbm2java
 */
public class Pacientes implements java.io.Serializable {

    private Long id;
    private String sip;
    private String dni;
    private String nombre;
    private String apellido1;
    private String apellido2;
    private String telefono;
    private String sexo;
    private Date fechaNacimiento;
    private String localidad;
    private Set citases = new HashSet(0);

    public Pacientes() {
    }

    public Pacientes(String sip, String dni, String nombre, String apellido1) {
        this.sip = sip;
        this.dni = dni;
        this.nombre = nombre;
        this.apellido1 = apellido1;
    }

    public Pacientes(String sip, String dni, String nombre, String apellido1, String apellido2, String telefono, String sexo, Date fechaNacimiento, String localidad, Set citases) {
        this.sip = sip;
        this.dni = dni;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.telefono = telefono;
        this.sexo = sexo;
        this.fechaNacimiento = fechaNacimiento;
        this.localidad = localidad;
        this.citases = citases;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSip() {
        return this.sip;
    }

    public void setSip(String sip) {
        this.sip = sip;
    }

    public String getDni() {
        return this.dni;
    }

    public void setDni(String dni) {
        this.dni = dni;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido1() {
        return this.apellido1;
    }

    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }

    public String getApellido2() {
        return this.apellido2;
    }

    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getSexo() {
        return this.sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public String getLocalidad() {
        return this.localidad;
    }

    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }

    public Set getCitases() {
        return this.citases;
    }

    public void setCitases(Set citases) {
        this.citases = citases;
    }

}
